"""empty message

Revision ID: befca2eb59e3
Revises: 2477e78c4247
Create Date: 2021-04-15 03:15:21.696379

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'befca2eb59e3'
down_revision = '2477e78c4247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'eye_color',
               existing_type=mysql.VARCHAR(length=70),
               nullable=True)
    op.alter_column('characters', 'gender',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('characters', 'hair_color',
               existing_type=mysql.VARCHAR(length=70),
               nullable=True)
    op.alter_column('characters', 'heigth',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('characters', 'name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.drop_index('eye_color', table_name='characters')
    op.drop_index('gender', table_name='characters')
    op.drop_index('hair_color', table_name='characters')
    op.drop_index('heigth', table_name='characters')
    op.drop_index('name', table_name='characters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'characters', ['name'], unique=True)
    op.create_index('heigth', 'characters', ['heigth'], unique=True)
    op.create_index('hair_color', 'characters', ['hair_color'], unique=True)
    op.create_index('gender', 'characters', ['gender'], unique=True)
    op.create_index('eye_color', 'characters', ['eye_color'], unique=True)
    op.alter_column('characters', 'name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('characters', 'heigth',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('characters', 'hair_color',
               existing_type=mysql.VARCHAR(length=70),
               nullable=False)
    op.alter_column('characters', 'gender',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('characters', 'eye_color',
               existing_type=mysql.VARCHAR(length=70),
               nullable=False)
    # ### end Alembic commands ###
