"""empty message

Revision ID: e780757b2d3d
Revises: 0f149979b7de
Create Date: 2021-04-22 03:01:17.171988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e780757b2d3d'
down_revision = '0f149979b7de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('character_id', sa.Integer(), nullable=True))
    op.add_column('favorites', sa.Column('planet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorites', 'planets', ['planet_id'], ['id'])
    op.create_foreign_key(None, 'favorites', 'characters', ['character_id'], ['id'])
    op.drop_column('favorites', 'fav_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('fav_name', mysql.VARCHAR(length=250), nullable=False))
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'planet_id')
    op.drop_column('favorites', 'character_id')
    # ### end Alembic commands ###
